spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/trampo
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/trampo
db.User=postgres
db.password=1234
api.security.token.secret=${JWT_SECRET:ambiente-dev-ryan}
